-- Indexes for frequently filtered and sorted application queries.
CREATE INDEX IF NOT EXISTS "User_role_status_idx" ON "User"("role", "status");
CREATE INDEX IF NOT EXISTS "User_createdAt_idx" ON "User"("createdAt");
CREATE INDEX IF NOT EXISTS "ParentStudentLink_parentId_isActive_idx" ON "ParentStudentLink"("parentId", "isActive");
CREATE INDEX IF NOT EXISTS "ParentStudentLink_studentId_isActive_idx" ON "ParentStudentLink"("studentId", "isActive");
CREATE INDEX IF NOT EXISTS "Material_topicId_status_idx" ON "Material"("topicId", "status");
CREATE INDEX IF NOT EXISTS "Material_authorId_status_idx" ON "Material"("authorId", "status");
CREATE INDEX IF NOT EXISTS "Material_status_updatedAt_idx" ON "Material"("status", "updatedAt");
CREATE INDEX IF NOT EXISTS "TkadTip_status_orderNo_idx" ON "TkadTip"("status", "orderNo");
CREATE INDEX IF NOT EXISTS "TkadTip_authorId_status_idx" ON "TkadTip"("authorId", "status");
CREATE INDEX IF NOT EXISTS "Blueprint_topicId_idx" ON "Blueprint"("topicId");
CREATE INDEX IF NOT EXISTS "Blueprint_periodCode_idx" ON "Blueprint"("periodCode");
CREATE INDEX IF NOT EXISTS "Blueprint_testGroup_idx" ON "Blueprint"("testGroup");
CREATE INDEX IF NOT EXISTS "Question_topicId_status_idx" ON "Question"("topicId", "status");
CREATE INDEX IF NOT EXISTS "Question_authorId_status_idx" ON "Question"("authorId", "status");
CREATE INDEX IF NOT EXISTS "Question_blueprintId_idx" ON "Question"("blueprintId");
CREATE INDEX IF NOT EXISTS "QuestionOption_questionId_idx" ON "QuestionOption"("questionId");
CREATE INDEX IF NOT EXISTS "Tryout_status_startAt_endAt_idx" ON "Tryout"("status", "startAt", "endAt");
CREATE INDEX IF NOT EXISTS "Tryout_authorId_status_idx" ON "Tryout"("authorId", "status");
CREATE INDEX IF NOT EXISTS "TryoutQuestion_questionId_idx" ON "TryoutQuestion"("questionId");
CREATE INDEX IF NOT EXISTS "Attempt_userId_startedAt_idx" ON "Attempt"("userId", "startedAt");
CREATE INDEX IF NOT EXISTS "Attempt_tryoutId_submittedAt_idx" ON "Attempt"("tryoutId", "submittedAt");
CREATE INDEX IF NOT EXISTS "Attempt_userId_tryoutId_submittedAt_idx" ON "Attempt"("userId", "tryoutId", "submittedAt");
CREATE INDEX IF NOT EXISTS "AttemptAnswer_questionId_idx" ON "AttemptAnswer"("questionId");
CREATE INDEX IF NOT EXISTS "AttemptAnswer_selectedOptionId_idx" ON "AttemptAnswer"("selectedOptionId");
CREATE INDEX IF NOT EXISTS "TryoutIncident_createdAt_idx" ON "TryoutIncident"("createdAt");
CREATE INDEX IF NOT EXISTS "TryoutIncident_tryoutId_createdAt_idx" ON "TryoutIncident"("tryoutId", "createdAt");
CREATE INDEX IF NOT EXISTS "TryoutIncident_attemptId_idx" ON "TryoutIncident"("attemptId");
CREATE INDEX IF NOT EXISTS "TryoutIncident_userId_createdAt_idx" ON "TryoutIncident"("userId", "createdAt");
